#!/usr/bin/env python3
from os import remove as rm
from os import system as run
from sys import exit
from subprocess import call
from os.path import isfile

from sys import argv as ARGS

exe = "/home/brice/dev/go-ws/src/byaigo/byaigo"

if "clean" in ARGS:
    rm(exe)

if "test" in ARGS:
    run("go test ~/dev/go-ws/src/byaigo/evaluator/")
    run("go test ~/dev/go-ws/src/byaigo/parser/")
    run("go test ~/dev/go-ws/src/byaigo/ast/")
    run("go test ~/dev/go-ws/src/byaigo/lexer/")
    run("go test ~/dev/go-ws/src/byaigo/code/")

if "build" in ARGS:
    run("go build ~/dev/go-ws/src/byaigo")

if "run" in ARGS:
    run("go build ~/dev/go-ws/src/byaigo")
    try:
        call(exe, shell=True)
    except KeyboardInterrupt:
        run("clear")
        if isfile(exe):
            rm(exe)
        exit()
