#!/usr/bin/env python3
import os
import sys
import subprocess


args = sys.argv


if "clean" in args:
    os.remove("/home/brice/dev/go-ws/src/byaigo/byaigo")

if "test" in args:
    os.system("go test ~/dev/go-ws/src/byaigo/evaluator/")
    os.system("go test ~/dev/go-ws/src/byaigo/parser/")
    os.system("go test ~/dev/go-ws/src/byaigo/ast/")
    os.system("go test ~/dev/go-ws/src/byaigo/lexer/")

if "build" in args:
    os.system("go build ~/dev/go-ws/src/byaigo")

if "run" in args:
    os.system("go build ~/dev/go-ws/src/byaigo")
    try:
        subprocess.call("/home/brice/dev/go-ws/src/byaigo/byaigo", shell=True)
    except KeyboardInterrupt:
        os.system("clear")
        sys.exit(0)
